package com.mobius.software.amqp.parser.state;

public enum EndpointState
{
	HDR_RCV, HDR_SENT, HDR_EXCH, OPEN_PIPE, OC_PIPE, OPEN_RCVD, OPEN_SENT, CLOSE_PIPE, CLOSE_RCVD, CLOSE_SENT, DISCARDING, END, UNMAPPED, BEGIN_SENT, BEGIN_RCVD, MAPPED, END_SENT, END_RCVD, START, OPENED;
}
